In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://www.cdc.gov/workplacehealthpromotion/data-surveillance/docs/whpps_120717.csv'
cdc = pd.read_csv(url, sep='~')
cdc

/tmp/ipykernel_141/4171161005.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  cdc = pd.read_csv(url, sep='~')

,OC1,OC3,HI1,HI2,HI3,HI4,HRA1,HRA1A,HRA1B,HRA1E,...,WL3_05,E1_09,Suppquex,Id,Region,CDC_Region,Industry,Size,Varstrata,"Finalwt_worksite,,,,"
0,7,3.0,2.0,1.0,2.0,1.0,1.0,3.0,4.0,2.0,...,PTO,NaN,2.0,217.0,1.0,2.0,7.0,7.0,0.0,"47.793940929,,,,"
1,2,3.0,2.0,3.0,1.0,1.0,1.0,3.0,3.0,1.0,...,NaN,NaN,1.0,326.0,3.0,7.0,7.0,6.0,0.0,"47.793940929,,,,"
2,7,3.0,1.0,3.0,1.0,1.0,1.0,3.0,97.0,2.0,...,NaN,NaN,1.0,399.0,4.0,8.0,7.0,8.0,0.0,"47.793940929,,,,"
3,1,2.0,1.0,2.0,1.0,1.0,97.0,96.0,96.0,96.0,...,NaN,NaN,1.0,475.0,5.0,9.0,7.0,4.0,0.0,"47.793940929,,,,"
4,2,3.0,1.0,3.0,1.0,1.0,1.0,3.0,3.0,2.0,...,NaN,NaN,1.0,489.0,2.0,4.0,7.0,4.0,0.0,"47.793940929,,,,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2838,1,4.0,1.0,3.0,1.0,1.0,2.0,96.0,96.0,96.0,...,NaN,NaN,2.0,29419.0,5.0,10.0,6.0,5.0,549.0,"421.28310196,,,,"
2839,7,4.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,...,NaN,NaN,1.0,53041.0,5.0,10.0,6.0,5.0,549.0,"421.28310196,,,,"
2840,2,4.0,2.0,3.0,1.0,1.0,1.0,3.0,2.0,2.0,...,NaN,NaN,1.0,7496.0,5.0,10.0,6.0,8.0,552.0,"62.86238594,,,,"
2841,1,4.0,2.0,3.0,1.0,1.0,1.0,2.0,97.0,2.0,...,NaN,NaN,2.0,18994.0,5.0,10.0,6.0,8.0,552.0,"76.460186994,,,,"
2842,2,4.0,2.0,3.0,1.0,1.0,1.0,1.0,3.0,2.0,...,NaN,Nothing is needed,2.0,27704.0,5.0,10.0,6.0,8.0,552.0,"62.86238594,,,,"

## Filter columns

In [3]:
cols_to_keep = ['Size', 'OC1', 'HPR9_1', 'HPR1_1A', 'HPR1_1', 'HS15_2', 'HPR2_3B', 'WD2']
cdc_clean = cdc[cols_to_keep]
cdc_clean

      Size OC1  HPR9_1  HPR1_1A  HPR1_1  HS15_2  HPR2_3B    WD2
0      7.0   7     2.0      3.0     1.0     1.0      1.0   85.0
1      6.0   2     2.0      3.0     1.0     1.0      1.0   90.0
2      8.0   7     1.0      1.0     1.0     1.0      1.0  997.0
3      4.0   1     2.0     96.0     2.0     9.0      1.0   50.0
4      4.0   2     2.0      3.0     1.0     1.0      1.0   60.0
...    ...  ..     ...      ...     ...     ...      ...    ...
2838   5.0   1    99.0      1.0     1.0    99.0      1.0  999.0
2839   5.0   7    97.0      3.0     1.0    96.0      1.0  997.0
2840   8.0   2     1.0      3.0     1.0     9.0      1.0   61.0
2841   8.0   1    99.0     99.0    99.0    99.0     99.0  999.0
2842   8.0   2     1.0      1.0     1.0     1.0      1.0   35.0

[2843 rows x 8 columns]

In [4]:
cdc_clean = cdc_clean.rename({'Size':'size', 'OC1':'department', 'HPR9_1':'sleep', 'HPR1_1A':'physact', 
                              'HPR1_1':'physprogram', 'HS15_2':'breastcancer', 'HPR2_3B':'vendfood', 'WD2':'percentfemale'},
                              axis = 1)
cdc_clean

,size,department,sleep,physact,physprogram,breastcancer,vendfood,percentfemale
0,7.0,7,2.0,3.0,1.0,1.0,1.0,85.0
1,6.0,2,2.0,3.0,1.0,1.0,1.0,90.0
2,8.0,7,1.0,1.0,1.0,1.0,1.0,997.0
3,4.0,1,2.0,96.0,2.0,9.0,1.0,50.0
4,4.0,2,2.0,3.0,1.0,1.0,1.0,60.0
...,...,...,...,...,...,...,...,...
2838,5.0,1,99.0,1.0,1.0,99.0,1.0,999.0
2839,5.0,7,97.0,3.0,1.0,96.0,1.0,997.0
2840,8.0,2,1.0,3.0,1.0,9.0,1.0,61.0
2841,8.0,1,99.0,99.0,99.0,99.0,99.0,999.0
2842,8.0,2,1.0,1.0,1.0,1.0,1.0,35.0

## Recode and collapse categories

In [5]:
cdc_clean['size'].value_counts()
# this is basically a frequency table

1.0    1175
2.0     655
3.0     365
4.0     263
8.0     160
5.0     130
6.0      66
7.0      28
Name: size, dtype: int64

In [6]:
size_replace = {1.0:'10-24',
                2.0:'25-49',
                3.0:'50-99',
                4.0:'100-249',
                5.0:'250-499',
                6.0:'500-749',
                7.0:'750-999',
                8.0:'1,000+'}
cdc_clean['size'] = cdc_clean['size'].replace(size_replace)
cdc_clean

,size,department,sleep,physact,physprogram,breastcancer,vendfood,percentfemale
0,750-999,7,2.0,3.0,1.0,1.0,1.0,85.0
1,500-749,2,2.0,3.0,1.0,1.0,1.0,90.0
2,"1,000+",7,1.0,1.0,1.0,1.0,1.0,997.0
3,100-249,1,2.0,96.0,2.0,9.0,1.0,50.0
4,100-249,2,2.0,3.0,1.0,1.0,1.0,60.0
...,...,...,...,...,...,...,...,...
2838,250-499,1,99.0,1.0,1.0,99.0,1.0,999.0
2839,250-499,7,97.0,3.0,1.0,96.0,1.0,997.0
2840,"1,000+",2,1.0,3.0,1.0,9.0,1.0,61.0
2841,"1,000+",1,99.0,99.0,99.0,99.0,99.0,999.0
2842,"1,000+",2,1.0,1.0,1.0,1.0,1.0,35.0

In [7]:
size_replace = {1.0:'10-24',
               2.0:'25-49',
               3.0:'50-99',
               4.0:'100-249',
               5.0:'250-499',
               6.0:'500-749',
               7.0:'750-999',
               8.0:'1,000+'}
cdc_clean['size'] = cdc_clean['size'].replace(size_replace)

 

department_replace = {'1':'Human Resources and/or Benefits', 
                      '2':'Health Promotion/Fitness/Wellness',
                      '3':'Safety',
                      '4':'Medical', 
                      '5':'PR/Marketing', 
                      '6':'Finance',
                      '7':'Other',
                      '97':np.nan,
                      '99':np.nan}
cdc_clean['department'] = cdc_clean['department'].astype('str').replace(department_replace)

 

vendfood_replace = {1.0: 'Yes',
                   2.0: 'No',
                   5.0: 'No',
                   96.0: np.nan,
                   97.0: np.nan,
                   98.0: np.nan,
                   99.0: np.nan}
cdc_clean['vendfood'] = cdc_clean['vendfood'].replace(vendfood_replace)

 

bc_replace = {1 : 'Yes',
                2: 'No',
                5 : 'No',
                9 : 'No',
                96 : np.nan,
                97 : np.nan,
                99 : np.nan}
cdc_clean['breastcancer'] = cdc_clean['breastcancer'].replace(bc_replace)

 


physact_replace = {1:'info',
               2:'Skillbuilding',
               3:'both',
               96:np.nan,
               97:np.nan,
               98:np.nan,
               99:np.nan}
cdc_clean['physact']=cdc_clean['physact'].replace(physact_replace) # The idea of replace is

 

sleep_replace = {1:'Yes',
                2:'No',
                5:'No',
                96:np.nan,
                97:np.nan,
                98:np.nan,
                99:np.nan}
cdc_clean['sleep'] = cdc_clean['sleep'].replace(sleep_replace)

 

physprograms_replace = {1.0:'Yes', 
                        2.0:'No', 
                        5.0:'No', 
                        99.0:np.nan, 
                        96.0:np.nan, 
                        97.0:np.nan, 
                        98.0:np.nan}
cdc_clean['physprogram'] = cdc_clean['physprogram'].replace(physprograms_replace)

percent_replace = {997:np.nan, 998:np.nan, 999:np.nan}
cdc_clean['percentfemale'] = cdc_clean['percentfemale'].replace(percent_replace)

cdc_clean

,size,department,sleep,physact,physprogram,breastcancer,vendfood,percentfemale
0,750-999,Other,No,both,Yes,Yes,Yes,85.0
1,500-749,Health Promotion/Fitness/Wellness,No,both,Yes,Yes,Yes,90.0
2,"1,000+",Other,Yes,info,Yes,Yes,Yes,NaN
3,100-249,Human Resources and/or Benefits,No,NaN,No,No,Yes,50.0
4,100-249,Health Promotion/Fitness/Wellness,No,both,Yes,Yes,Yes,60.0
...,...,...,...,...,...,...,...,...
2838,250-499,Human Resources and/or Benefits,NaN,info,Yes,NaN,Yes,NaN
2839,250-499,Other,NaN,both,Yes,NaN,Yes,NaN
2840,"1,000+",Health Promotion/Fitness/Wellness,Yes,both,Yes,No,Yes,61.0
2841,"1,000+",Human Resources and/or Benefits,NaN,NaN,NaN,NaN,NaN,NaN
2842,"1,000+",Health Promotion/Fitness/Wellness,Yes,info,Yes,Yes,Yes,35.0

In [8]:
cdc_clean['department'].value_counts()

Other                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1464
Human Resources and/or Benefits                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               876
Finance                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       125
Health Promotion/Fitness/Wellness                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             109
Safety                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         83
Medical                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        32
PR/Marketing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   14
1~4~2~1~2~1~2~96~96~96~1~1~1~1~1~1~5~3~1~5~96~2~1~1~1~1~2~1~1~1~97~1~1~1~2~1~1~2~2~2~2~2~2~10~3~1~3~3~4~1~1~2~2~1~1~2~2~2~1~2~1~3~3~2~1~2~2~1~2~2~1~2~2~2~1~2~2~1~3~3~97~2~1~1~3~1~2~2~97~97~97~1~1~2~2~1~1~1~2~1~1~97~1~2~96~96~96~2~96~96~96~2~96~96~96~2~96~96~96~1~1~2~1~1~1~1~1~1~1~1~1~1~97~96~2~9~1~1~2~4~3~97~97~97~97~97~97~2~2~1~2~2~1~97~97~97~97~97~97~2~2~1~2~2~1~2~2~1~97~97~97~4~2~2~3~96~96~96~96~96~96~96~96~96~96~96~~1~2~1~2~1~2~1~2~2~1~2~97~2~2~2~2~4~5~2~1~2~4~2~1~2~3~2~1~1~1~1~1~1~2~2~1~2~1~2~2~1~2~2~2~2~2~8~997~997~997~100~90~80~90~997~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~~0~~"Additional sick benefits for Fire Fighters as per Louisiana law ""In-Service Sick"" Leave."~~2~0000020651~2~6~6~5~325~583.71332776,,,,       1
Name: department, dtype: int64

In [12]:
cdc_clean.groupby('department').size()

department
1~4~2~1~2~1~2~96~96~96~1~1~1~1~1~1~5~3~1~5~96~2~1~1~1~1~2~1~1~1~97~1~1~1~2~1~1~2~2~2~2~2~2~10~3~1~3~3~4~1~1~2~2~1~1~2~2~2~1~2~1~3~3~2~1~2~2~1~2~2~1~2~2~2~1~2~2~1~3~3~97~2~1~1~3~1~2~2~97~97~97~1~1~2~2~1~1~1~2~1~1~97~1~2~96~96~96~2~96~96~96~2~96~96~96~2~96~96~96~1~1~2~1~1~1~1~1~1~1~1~1~1~97~96~2~9~1~1~2~4~3~97~97~97~97~97~97~2~2~1~2~2~1~97~97~97~97~97~97~2~2~1~2~2~1~2~2~1~97~97~97~4~2~2~3~96~96~96~96~96~96~96~96~96~96~96~~1~2~1~2~1~2~1~2~2~1~2~97~2~2~2~2~4~5~2~1~2~4~2~1~2~3~2~1~1~1~1~1~1~2~2~1~2~1~2~2~1~2~2~2~2~2~8~997~997~997~100~90~80~90~997~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~95~~0~~"Additional sick benefits for Fire Fighters as per Louisiana law ""In-Service Sick"" Leave."~~2~0000020651~2~6~6~5~325~583.71332776,,,,       1
Finance                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       125
Health Promotion/Fitness/Wellness                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             109
Human Resources and/or Benefits                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               876
Medical                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        32
Other                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1464
PR/Marketing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   14
Safety                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         83
dtype: int64

In [18]:
cdc_clean.groupby(['size','breastcancer']).agg({'percentfemale':'mean'})#.reset_index()

                      percentfemale
size    breastcancer
1,000+  No                65.400000
        Yes               68.594595
10-24   No                47.959756
        Yes               58.275862
100-249 No                56.911290
        Yes               59.444444
25-49   No                44.644647
        Yes               59.500000
250-499 No                58.472727
        Yes               71.833333
50-99   No                51.512690
        Yes               57.680000
500-749 No                61.210526
        Yes               63.000000
750-999 No                60.500000
        Yes               69.333333